README.md
Primer commit en repositorio App- Agrego README.MD a develop
=> Primer commit en repositorio App- Agrego README.MD a develop

app/src/main/res/layout/activity_splash.xml
agrego icono a Activity Splash
=> agrego icono a Activity Splash

app/src/main/AndroidManifest.xml
=> Configurando ActivitySplash

app/src/main/java/com/capacitapp/SplashActivity.java
sigo configurando SplashActivity
=> sigo configurando SplashActivity

app/src/main/AndroidManifest.xml, app/src/main/java/com/capacitapp/ContactoActivity.java, app/src/main/res/layout/activity_contacto.xml
=> agrego Ativity Contacto

app/src/main/res/layout/activity_contacto.xml
=> editando Activity Contacto

app/src/main/res/layout/activity_contacto.xml
=> configurando vista Contacto

app/src/main/res/layout/activity_contacto.xml, app/src/main/res/values/strings.xml
configurando vista Contacto con sus strings
=> configurando vista Contacto con sus strings

app/src/main/res/values-night/themes.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
Agrego colores para la aplicación
=> Agrego colores para la aplicación

app/src/main/res/layout/activity_contacto.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_registro.xml
agrego toolbar en vistas creadas de app: Registro y Main
=> agrego toolbar en vistas creadas de app

app/src/main/res/layout/activity_login.xml
agrego toolbar idem a perfil en vista login
=> agrego toolbar idem a perfil en vista login

app/src/main/AndroidManifest.xml, app/src/main/java/com/capacitapp/ConfiguracionActivity.java, app/src/main/res/layout/activity_configuracion.xml, app/src/main/res/values/strings.xml
=> Creo Activity configuración

app/src/main/res/values/themes.xml
=> prueba de colores de app

app/src/main/AndroidManifest.xml, app/src/main/java/com/capacitapp/InicioActivity.java, app/src/main/res/layout/activity_inicio.xml
=> creo ActivityIncio

app/src/main/java/com/capacitapp/MainActivity.java, app/src/main/java/com/capacitapp/PerfilActivity.java, app/src/main/java/com/capacitapp/loginActivity.java
configuro conexiones de login a Registro y de Perfil a Configuración
=> configuro conexiones de login a Registro y de Perfil a Configuración

app/src/main/AndroidManifest.xml, app/src/main/java/com/capacitapp/EliminarCuentaActivity.java, app/src/main/res/layout/activity_eliminar_cuenta.xml, app/src/main/res/values/strings.xml
agrego Activity Eliminar cuenta
=> agrego Activity Eliminar cuenta

app/src/main/java/com/capacitapp/EliminarCuentaActivity.java, app/src/main/java/com/capacitapp/PerfilActivity.java, app/src/main/res/layout/activity_eliminar_cuenta.xml
conecto Texto eliminar cuenta de perfil con Activity EliminarCuenta
=> conecto Texto eliminar cuenta de perfil con Activity EliminarCuenta

app/src/main/res/layout/activity_eliminar_cuenta.xml
=> edito vista Eliminar Cuenta

.idea/appInsightsSettings.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/capacitapp/EliminarCuentaActivity.java, app/src/main/java/com/capacitapp/PerfilActivity.java, app/src/main/res/layout/activity_eliminar_cuenta.xml, app/src/main/res/values/strings.xml
Agrego Activity EliminarCuenta y reestablezco conexiones borradas
=> Agrego Activity EliminarCuenta y reestablezco conexiones borradas

app/src/main/java/com/capacitapp/PerfilActivity.java
mostrar dato:nombre en el Perfil
=> mostrar dato:nombre en el Perfil
